name: Cypress Testing

on: [push]

jobs:
  cypress-run :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.x.xd
        with:
          build: npm run build
          start: npm start